publisher confirm
makasim/amqpextra pull request #43
Opened 2020-11-05 15:08 UTC by cat-in-vacuum

2020-11-05 15:54 UTC, makasim commented
add func for hanlding confimations: 

```
func (p) handleConfirmations() {
}
```

and run it in separate gorouting just like `go p.connectionState()`

2020-11-05 15:56 UTC, makasim requested changes

2020-11-05 15:56 UTC, makasim commented on publisher/publisher.go
> +	conformationChs []AMQPChannel
define prop

```
confirmationCh chan <-chan error // resultCh
```

2020-11-05 15:56 UTC, makasim commented on publisher/publisher.go
> +func WihConfirmation(confirmation bool) Option {
typo `WihConfirmation` -> `WithConfirmation`

2020-11-05 15:56 UTC, makasim commented on publisher/publisher.go
> +func WihConfirmation(confirmation bool) Option {
```go
func WithConfirmation(buffer int) Option {
```

buffer is the conformationChs size
validate that buffer is greater than 1. 
make conformationChs with given size

2020-11-05 15:56 UTC, makasim commented on publisher/publisher.go
> +	if p.confirmation {
```
p.conformationChs != nil
```

2020-11-05 15:56 UTC, makasim commented on publisher/publisher.go
> +		err := ch.Confirm(false)
enable confirmation in `channelState`  just after successful init call

2020-11-05 15:56 UTC, makasim commented on publisher/publisher.go
> +		err := ch.Confirm(false)
in case of err wait and retry

2020-11-05 15:56 UTC, makasim commented on publisher/publisher.go
> +
```
if result != nil {
  return reply()
}

if p.confirmationCh != nil {
  select {
  case p.confirmationCh <- msg.resultCh:
  case <-p.ctx.Done():
    return reply(p.ctx.Err())
  }
}
```

2020-11-05 20:12 UTC, makasim commented
fixes https://github.com/makasim/amqpextra/issues/3

2020-11-06 11:03 UTC, makasim requested changes

2020-11-06 11:03 UTC, makasim commented on publisher/publisher.go
> +				if c.Ack {
```go
resultCh := <-confirmationCh

if c.Ack {
    resultCh <- nil
} else {
    resultCh <- fmt.Errorf("not delivered")
}
```

2020-11-06 13:10 UTC, makasim requested changes

2020-11-06 15:26 UTC, cat-in-vacuum commented on publisher/publisher.go
> +				for {
Can resultCh <- amqp.ErrClosed be moved to separate method?

2020-11-06 16:01 UTC, makasim requested changes

2020-11-06 16:14 UTC, makasim commented
e2e publish confirms enabled. publish ten messages and assert that result is nil

2020-11-10 18:16 UTC, makasim requested changes

2020-11-10 18:16 UTC, makasim commented on publisher/publisher_test.go
> +	main.Run("WaitIfChannelConfirmErrored", func(t *testing.T) {
WaitRetryIfConfirmErrored

2020-11-10 18:16 UTC, makasim commented on publisher/publisher_test.go
> +		close(confirmationCh)
`defer close(confirmationCh)` just after `confirmationCh := make(chan amqp.Confirmation, 2)`

2020-11-10 18:16 UTC, makasim commented on publisher/publisher_test.go
> +	main.Run("ResultNilIfConfirmed", func(t *testing.T) {
AckConfirmTwoMessages

2020-11-10 18:16 UTC, makasim commented on publisher/publisher_test.go
> +	main.Run("ResultErroredIfNotConfirmed", func(t *testing.T) {
NackConfirmTwoMessages

2020-11-10 18:16 UTC, makasim commented on publisher/publisher_test.go
> +		require.EqualError(t, waitResult(resultCh, time.Millisecond*100), "not delivered")
`not delivered` ->  `confirmation: nack`

2020-11-10 18:16 UTC, makasim commented on publisher/publisher_test.go
> +		close(confirmationCh)
in this test you should not do it.

2020-11-10 18:16 UTC, makasim commented on publisher/publisher_test.go
> +	main.Run("ResultErroredWhenConfirmationClosed", func(t *testing.T) {
ConfirmationWhileConnectionClosed

2020-11-10 18:16 UTC, makasim commented on publisher/publisher_test.go
> +	main.Run("AllMessagesGetConfirmationWhenConnectionClosed", func(t *testing.T) {
ConfirmationWhileChannelClosed

2020-11-11 17:11 UTC, merged